name: Start FoD scan

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: fortify/gha-setup-scancentral-client@v1
      - uses: fortify/gha-setup-fod-uploader@v1
      - run: scancentral package -bt mvn -o package.zip
      - run: java -jar $FOD_UPLOAD_JAR -z package.zip -aurl $FOD_AURL -purl $FOD_PURL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" -ep 2 -pp 1
        env: 
          FOD_AURL: ${{ secrets.FOD_EIGHTBALL_API_URL }}
          FOD_PURL: ${{ secrets.FOD_EIGHTBALL_BASE_URL }}
          FOD_TENANT: ${{ secrets.FOD_EIGHTBALL_TENANT }}  
          FOD_USER: ${{ secrets.FOD_EIGHTBALL_USER }}
          FOD_PAT: ${{ secrets.FOD_EIGHTBALL_PAT }}
          FOD_RELEASE_ID: ${{ secrets.FOD_EIGHTBALL_RELEASE_ID }} 
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: scancentral-logs
          path: ~/.fortify/scancentral/log
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: package.zip
          path: package.zip
